i-love-flamingo/flamingo

core/oauth/Readme.md
Module was renamed from auth to oauth, therefore config namespace changed. This PR updates readme accordingly.
=> core/oauth: Update Readme.md to match actual module code

framework/opencensus/module.go, framework/systemendpoint/module.go
metrics endpoint is not available on multi-area setups with prefix router.
The map binding to systemendpoit has to be done on each call of opencensus' Configure().
=> Fix metrics endpoint

framework/systemendpoint/Readme.md, framework/web/routescmd.go
routes and handler commands fail with nil pointer runtime error (tries to access router.routerRegistry  )
probably due to former refactorings of router.
(We should add functional tests for the commands)
=> fix failing routes and handler commands

core/oauth/Readme.md, core/oauth/application/authmanager.go, core/oauth/interfaces/callback_controller.go, framework/web/handler.go, framework/web/router.go, framework/web/router_test.go
Observations:
* Accesstoken seems to be empty in some cases (e.g. error in oauth2 provider)
Other Issues:
* The openid token is saved only once in callback controller in the session
* services that need to get the accesstoken do this normaly by:
```
1 auth = authmanager.Auth()
2 token = auth.TokenSource.Token()
3 token.AccessToken
```
1 gets tokensource from saved oauth2 token in session
- how does that work since a reference is supposed to be saved in session:
- after writing the session?
- in cluster setup?
(imho pointer should never be saved in session)
2  this call will renew the token if it is expired - but never saved back to session
Solution:
* Whenever a consumer calls  authmanager.Auth() - he should get is based on an eventually renewed "new" Token
* write no pointer in session
=> handle accesstoken empty edge cases

core/locale/Readme.md, core/locale/interfaces/templatefunctions/label.go, core/locale/interfaces/templatefunctions/priceFormat.go, core/locale/interfaces/templatefunctions/priceFormatLong.go, core/locale/interfaces/templatefunctions/priceFormatLong_test.go, core/locale/interfaces/templatefunctions/priceFormat_test.go
Price format functions now support all types that the underlying [accounting](https://github.com/leekchan/accounting) module supports.
- Add tests for price related template functions
- Update readme to include better examples
=> core/locale: Add support for various number types in price format template function

app.go, framework/cmd/Readme.md, framework/cmd/module.go, framework/config/loader.go, framework/config/module.go, go.mod, go.sum
persistent flags for the root command can now be registered via dingo.
The broken flags of the config module are fixed by using this.
=> framework/cmd, framework/config: fix flag usage

framework/web/router.go, framework/web/router_test.go
The usage of this config value has been dropped accidentally
during v3 refactoring work
=> web: use session.name config actually for the session name

framework/systemendpoint/application/server.go
Currently Systemendpoint starts with "serve" command.
But there are cases where one want an own command but still run the Systemendpoint.
=> Systemendpoint should be used individually

core/gotemplate/engine.go, core/gotemplate/module.go, core/gotemplate/templatefunctions.go
It's not suitable to enter maps form a gotemplate file, so the functions
take the map as variadic arguments alternating between key and value.
On top there was no possibility to print unescaped HTML and JS which can
now be done with the plainHTML and plainJS template functions.
=> gotemplate: more convenient usage of template functions

core/oauth/application/userservice.go
Strangely all user service methods have the session as a parameter but the getUser() method still tries to get the session from the context request. This leads to a potential nil pointer access if the context does not contain a request.
=> oauth: Fix potential nil pointer if context has no request

core/oauth/Readme.md, core/oauth/domain/mapping.go, core/oauth/domain/mapping_test.go
There are cases where properties need to be mapped from different claim keys.
This change propose to configure multiple fields with ";" seperated
=> oauth: support multiple claim keys in mapping config

framework/cmd/module.go
Currently all commands are not stopping unless you hit STRG-C
This is because the rootcommand inherits the PersistentPostRun which always blocks until termination signal is send.
Proposal A) 
We can send own signal in all commands that should stop immediatelly (see commit)
Proposal B)
The root command should not block
Instead it should just trigger the ShutdownEvent in its PersistentPostRun
Then it is the job of the "serve" command to handle the interruption
Thoughts?
=> Commands not stopping

core/locale/Readme.md, core/locale/application/priceService.go, core/locale/interfaces/templatefunctions/priceFormat.go, core/locale/interfaces/templatefunctions/priceFormatLong_test.go, core/locale/interfaces/templatefunctions/priceFormat_test.go, core/locale/module.go
flamingo_commerce introduced a priceService to format prices and allows to configure formatting per currency.
This should move to locale package.
(later flamingo_commerce can use this service instead of own)
=> locale: add price service for formatting

framework/web/templatefunctions.go
When checking URLs like "/en/category/mycategory" the external URL checker returns true although it is a relative URL meaning it is not external.
=> Check potential external URL for relative URL structure (no host in URL)

framework/config/loader_test.go, framework/config/module.go
after manipulating the global flag set from within a test, it must be
reinitialized in tear down to assure an empty set for the next tests
=> config: make tests more robust

core/oauth/application/authmanager.go, core/oauth/module.go
Oauth and authmanager might be an dependency for other modules (e.g. cart module)
But if "login" is never used for a certain project the current authmanager will always pani of no valid OIDC provider is configured.
So this PR suggest to allow to disable the oidc feature by a flag.
Its a intermediate solution until the major new auth concept is included.
=> Add config to disable OIDC

framework/config/area.go
In case when prefixrouter module is required, dingo injector is initialised two times, which means that Config methods from all modules are called multiple times as well.
This call error message in logging (not panic, but just error logging) for module https://github.com/i-love-flamingo/domainserviceintercept because there is server initialisation in Config method of dsi module.
=> dingo injector is initialised 2 times when prefixrouter module is required

core/gotemplate/engine.go, core/gotemplate/engine_test.go, core/gotemplate/testdata/test-nested-dirs/dir-a/sub-dir-a/main.html, core/gotemplate/testdata/test-nested-dirs/layouts/base.html, core/gotemplate/testdata/test-nested-dirs/layouts/dir-a/layout1.html, core/gotemplate/testdata/test-simple/additional-template-funcs.html, core/gotemplate/testdata/test-simple/built-in-template-funcs.html, core/gotemplate/testdata/test-simple/simple.html, go.mod
Add tests for the engine
Fix mutex staying locked in case of error which can lead to a deadlock
Fix template function `map` causing out of bounds error if called with not enough arguments
=> core/gotemplate: Add engine tests, unlock mutex in case of error

framework/config/Readme.md, framework/config/loader.go, framework/config/loader_test.go, framework/config/testdata/contextfile/config_a.yml, framework/config/testdata/contextfile/context.yaml, framework/config/testdata/contextfile/cuetest.cue
This PR fixes various issues introduced during the new cue config refactoring:
- CONTEXTFILE contains the full file path including the extension. To be backward compatible, we have to remove the extension, because the current solution adds an extension that leads to path/to/file.yml.yml
- Loading cue files from CONTEXTFILE was not possible due to missing cueBuildInstance in the root area.
- Before the refactor you could use any file extension for the additional config files, we should now at least support .yml and .yaml, since both are widely used and the latter is preferred according to https://yaml.org/faq.html.
- Test cases / test data for CONTEXTFILE were missing
=> config: Fix config loading from CONTEXTFILE env

app.go, app_before1.13.go
For better black box testing of an Flamingo App its currently hard to run an App with the core logic - since everything happens inside App() method 
If we split the logic its possible to get an fully initialized area (that can be used to get initialised injector etc)
=> Extract app init

framework/prefixrouter/module.go
Using the legacy config for the prefixrouter currently leads to the following error due to wrong path:
`app: config load: root: cue: marshal error at path flamingo.prefixrouter.rootRedirectHandler.redirectTarget: cannot convert incomplete value "string" to JSON`
=> framework/prefixrouter: Fix wrong legacy config alias

framework/systemendpoint/application/server.go
ListenAndServe returns ErrServerClosed on regular shutdown
which results in a panic here on each flamingo app shutdown
=> systemendpoint: do not panic on regular shutdown

core/oauth/application/authmanager.go, core/oauth/interfaces/callback_controller.go
As long as the abandoned auth manager isn't replaced by the new auth module, we will reduce the log level of errors during token refresh from Error to Debug.
=> oauth: Rework log levels to avoid log pollution

docs/0. Introduction/1. Getting Started.md, docs/1. Flamingo Basics/2. Flamingo Project Structure.md
Fix the broken links in the Flamingo documentation
=> docs: fix missing/broken links

framework/config/Readme.md
integer injection is possible as well now.
=> framework/config: remove obsolete note for number config injection

Readme.md, examples/dist/Dockerfile, framework/flamingo/flamingo.go, framework/systemendpoint/application/server.go
Example:
```
go build -ldflags "-X flamingo.me/flamingo/v3/framework/flamingo.appVersion=1.5.3-321" -o app .
```
Result:
```
version: 1.5.3-321
go: go1.14.4
path: flamingo.me/test/example-portal
flamingo: v3.1.7-0.20200128092458-a827e5897b01
```
=> add systemserver version endpoint

framework/web/router.go
Adding a AreaRoutedEvent that is fired when the framework router starts.
This can be used to react on a per routed ChildArea
=> framework: Add AreaRoutedEvent

core/oauth/interfaces/callback_controller.go
Its possible to use multiple logins on the same device, for this case the previous session data should be cleaned up on a fresh login callback.
=> oauth: cleanup session data on login callback

app.go, framework/systemendpoint/application/server.go
* prevent system endpoint shutdown from being called multiple times
* degrade loglevel of main server shutdown to info, since this is the expected behaviour on SIGINT or SIGTERM
=> better handling of server closing during graceful shutdown

app.go, framework/cmd/module.go, framework/prefixrouter/module.go
The prefix router module was listening to the wrong event and therefore was never shut down. This resulted in a hanging state after pressing CTRL+C.
Since there are two ways of shutting down a command (signal for infinite command, post-run for a finite command) using the signal lead to a duplicate call of the shutdown function/log output. This is now wrapped in sync. Once to only trigger the shutdown once.
In addition, the default serve command tried to shutdown it's server independent of if it was running, this is now also checked to avoid confusing log outputs.
=> framework: Fix graceful shutdown that was blocked by prefix router, avoid duplicated log's

framework/web/docs/ReadmeRouter.md, framework/web/filter.go, framework/web/filter_test.go
Added option for web.Filter to be prioritised. By default, priority for all filters is 0, until it's specified differently. During web.ChainFilter initialisation, filters are stored in descending order.
=> framework/web: add sorting option for filters

app.go
This change allows to configure the listened port with default flamingo config. I kept the `-a` parameter for the `serve` command for backward compatibility. We can think about removing it in the future, because it's possible to use the `--flamingo-config "core.serve.port: 3322"` parameter instead.
=> servemodule: allow port configuration with flamingo config

core/auth/webidentity.go
When you call the login route you can either specify a redirect URL (via a query param) or the referer is taken into account.  [controller.go:36](https://github.com/i-love-flamingo/flamingo/blob/master/core/auth/controller.go#L36)
If you call the login route directly and don't provide the query param nor have a referer set, during saving of the redirect URL, a second fallback kicks in and takes the current URL and stores it as the redirect URL. [webidentity.go:143](https://github.com/i-love-flamingo/flamingo/blob/master/core/auth/webidentity.go#L143)
This second fallback leads to a redirect loop since after a successful login you are redirected back to the login and again and again...
=> core/auth: Fix potential redirect loop on login

framework/web/handler.go, framework/web/request.go
This code adds handler name attribute to web.Request and so possibility to have information if there is assigned handler and it's name later in ChainFilter, Middleware or Controller.
=> framework/web: add handler as part of request

framework/config/config_test.go, framework/config/loader.go
In case the config parsing fails flamingo panics.
Would be helpful to see the context (print the error lines)
=> framework/config: add printError before panic

.github/workflows/main.yml
Nancy currently prevents us from merging open pull requests, the vulnerabilities found mostly affect sub-dependencies we often have no control over. Sometimes it takes quite a long time until the maintainers of those packages publish a corresponding tag to which we can then update.
This PR removes Nancy from the main pipeline. The check is still running once a day.
=> ci: Remove Nancy from main pipeline

CHANGELOG.md, core/locale/application/label_service.go, core/locale/infrastructure/translation_service.go, core/locale/interfaces/controllers/translation_controller.go, core/locale/module.go
Fixes #188 and fixes #193. With the change we only reload the translations if one of the translationfiles changed. Only applies for debug mode, in production mode we still just load them once.
=> core/locale: fix data race and improve devmode performance in translation service

framework/prefixrouter/front_router.go, framework/prefixrouter/front_router_test.go
The front router truncates the prefix in the path and creates a new request. To do this the `url.Parse` function is used. If an invalid path is processed a nil pointer occurs.
This PR changes the behavior and returns a 404 page if an invalid path is used in the request.
fixes #198
=> framework/prefixrouter: Fix potential nil pointer when using malformed requests

core/auth/Readme.md, core/auth/mock/identity.go, core/auth/oauth/module.go, core/auth/oauth/module_test.go, core/auth/oauth/oidc.go, core/oauth/application/authmanager.go, core/oauth/domain/mapping.go, core/oauth/domain/user.go, core/oauth/interfaces/legacyIdentifier.go, go.mod, go.sum
According to the OpenID Connect specs, the /.well-known/openid-configuration should contain an `issuer` field that matches the URL used to fetch the configuration metadata:
> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.
https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
The OIDC solutions provided from Azure for example when using the Azure Active Directory B2C currently doesn't adhere to the OpenID Connect spec and returns a wrong issuer.
Since that's something they won't fix that fast (or maybe not even at all) we should introduce a configuration to support overriding the issuer URL. …
=> core/auth: update to recent go-oidc v3, allow oidc issuer URL override

core/auth/oauth/oidc.go, core/auth/oauth/oidc_test.go
Currently mapping access token claims is behaving wrong. Instead of actual access token claims the mapper maps token claims.
This change unpacks the access token and maps them, but still uses the existing behaviour to not ensure breaking something
=> fix(oauth): correctly map access-token claims

core/auth/oauth/oidc.go, core/oauth/interfaces/login_controller.go, go.mod, go.sum
Switch from `github.com/satori/go.uuid` to `github.com/gofrs/uuid`. 
fixes #225
=> chore(auth): switch to github.com/gofrs/uuid

app.go, framework/prefixrouter/module.go, framework/systemendpoint/application/server.go
=> fix(framework): use real port for server start event

framework/flamingo/ReadmeSession.md, framework/flamingo/sessions.go, framework/flamingo/sessions_test.go
The redis store is waiting internally on a ping response on creation. This feature adds a controllable timeout for it.
=> feat(session): add timeout for redis connection

.github/workflows/golangci-lint.yml, .github/workflows/main.yml, .golangci.yml
Add linter with discussed rules. Only newly introduced issues should be blocking the pipeline
=> ci: add golangci-lint to pipeline

core/auth/oauth/oidc.go, core/auth/oauth/oidc_test.go
In some cases you want to handle errors that happen during the OIDC callback differently.
A use case could be authenticating the user using the `prompt=none` flow which can result in a `error=login_required` on the Callback endpoint if the user is not already signed in with the identity provider. In this case you might want to redirect the user or display a specific error page.
The handler is optional and if it can't handle the error the build in logic kicks in.
=> feat(core/auth/oauth): Add optional OIDC callback error handler

core/auth/oauth/oidc.go, core/auth/oauth/oidc_test.go
By mistake, the newly introduced interface was not properly declared as optional but rather looked for an instance that was annotated with the name `optional`.
During testing, I also realized that it would make sense to have the original return URL within the function. 
Since this interface was introduced with the release yesterday and was not working at all I'll flag this only as a fix.
=> fix(core/auth/oauth): Properly mark OIDC callback error handler as optional

core/auth/oauth/oidc.go, core/auth/oauth/oidc_test.go
Currently, it is only possible to modify the authorization URL using the `AuthCodeOptioner` interface. Since the Exchange function also supports this pattern we should also pass the registered `AuthCodeOptioner` to it.
For example, both my authorization and my token retrieval endpoint need some custom URL param to work. Only the one for the auth endpoint would currently be possible.
=> feat(core/auth/oidc): Add support of `AuthCodeOption` in the token exchange during callback

core/silentzap/logger.go, core/zap/logger.go
Actually we count each call to the log functions even if the configured log level is higher
=> fix(zap): only record log metrics when we actually log something

.github/workflows/daily.yml, .github/workflows/golangci-lint.yml, .github/workflows/main.yml, .github/workflows/semanticore.yml
remove matrix strategy from jobs where we only check one go version
=> ci: force on latest go version & cleanup jobs

core/auth/oauth/module.go, core/auth/oauth/oidc.go, core/auth/oauth/oidc_test.go
By default we invalidate all state params that are older than 30min, this means if you spent 30min on the login page of the identity provider and then came back to flamingo you would be greeted by a lovely state mismatch error.
Reasons for spending such a long time at the OIDC provider could be for example creating a new account with various verification steps.
Introducing a config to support long-running login/registrations. If not specified we'll stick to 30min.
=> feat(oidc): Make state timeout duration configurable to support long taking sign in

core/auth/oauth/oidc.go, core/auth/oauth/oidc_test.go, core/requestlogger/logger_test.go, framework/module.go, framework/web/result.go
Using HTTP status code `500` for all issues occurring during the OIDC flow might not be the best way. Therefore changing at least the errors that can occur during the callback e.g. tinkered/missing state param as HTTP status `400`.
Additionally extending the web responder with error funcs that also take the ctx to enhance the logging for better traceability.
=> feat(auth/oidc): Use BadRequest response for state mismatches, enhance logging with context

framework/opencensus/sampler.go
`allowParentTrace` is misleading, this actually controls if the parent's sampling decision is evaluated or not (in public server scenarios, you might not want to allow public traces)
=> fix(opencensus): rename to ignoreParentDecision

framework/flamingo/flamingo.go, framework/flamingo/flamingo_test.go, framework/flamingo/versioncmd.go, framework/module.go, framework/module_test.go, framework/systemendpoint/application/server.go
This PR adds a version command to the default Flamingo CLI commands. It also refactors /version endpoint of the system_endpoint to use a function for printing different useful infos about application (application version set via ldflags, Git revision, version of the Go runtime etc.). The same function is used for the CLI command.
```
$ myapp version
App version:	1.2.3
Go runtime version:	go1.23.3
VCS revision:	2c8efce6b95f0216be3834270022cd53bef45300
Path:	go.aoe.com/whitelabel-airline/flamingo
Flamingo version:	v3.11.0
```
=> Add version command to the default framework CLI commands

.golangci.yml, .mockery.yaml, app.go, core/security/application/doc.go, core/security/application/role/doc.go, core/security/application/voter/doc.go, core/security/domain/doc.go, core/security/domain/mocks/permission_set.go, core/security/domain/mocks/role.go, core/security/interface/middleware/doc.go
1. Edited mockery configuration to use packages
2. Removed go:generate annotations scattered across the code
3. Edited linter config (replaces deprecated linter names with the new ones)
=> chore: edit mockery and linter configuration

framework/flamingo/ReadmeSession.md, framework/flamingo/healthcheck/redisSession.go
Edit description of sessions module to mention that any Redis-compatible cache can be used
=> chore: edit description of sessions module

app.go, app_test.go, framework/cmd/module.go, framework/cmd/module_test.go
This PR adds some tests to cover command execution and triggering startup and shutdown events. In order to enable testing it introduces some minor refactoring of error handling and graceful shutdown
=> Add tests for event dispatch when running commands and graceful shutdown

core/zap/module.go
as described in https://github.com/i-love-flamingo/flamingo/issues/511
Make zap logger caller skip configurable so source field shows the actual stack level from users application
=> feat: zap logger caller skip configurable
