app.go, framework/prefixrouter/module.go, framework/prefixrouter/module_test.go
=> dispatch ServerStartEvent and ServerShutdownEvent on serve command

core/oauth/Readme.md, core/security/interface/middleware/securityMiddleware.go
After login redirect url made in security module had double slashes in the end.
=> fix redirect url after login

core/locale/application/dateTimeService.go, core/locale/domain/dateTime.go
Add new method to override default time zone location.
=> Update date time formatter

framework/web/router_test.go
Fix some linter warnings within the router_test.go
=> Fix linter warnings

docs/0. Introduction/1. Getting Started.md, docs/1. Flamingo Basics/2. Flamingo Project Structure.md, docs/3. Core Modules/Auth (OpenId Connect).md, docs/3. Core Modules/OAuth (OpenId Connect).md
Documentation Links were broken, Symlink for auth module was missing/broken.
=> Fixing Links, broken symlink

framework/prefixrouter/front_router.go, framework/prefixrouter/front_router_test.go
On ambiguous matches the selected route should be deterministic.
The old behaviour using a map range leads to a random routing.
=> prefixrouter: use longest prefix if we have ambiguous matches

core/oauth/interfaces/fake/callback_controller.go, core/oauth/module.go
Extending the fakelogin callback with the option to support customer groups
=> [TASK] add option to add a specific usergroup during fakelogin

core/gotemplate/templatefunctions.go, core/gotemplate/templatefunctions_test.go
This adds tests for the templatefucntions used in the gotemplate module
=> core/gotemplate: Add template function tests and fix array out of bounds

core/locale/application/labelService.go, core/locale/domain/label.go, core/locale/infrastructure/translationService.go, core/locale/interfaces/controllers/translation.go, core/locale/interfaces/templatefunctions/priceFormatLong_test.go, core/locale/interfaces/templatefunctions/priceFormat_test.go, core/locale/module.go
Simple API endpoint which returns all translations as.
=> Add API endpoint to get all translations

go.mod, go.sum
The accounting library had an error regarding zeroFormat. It's fixed with the new version.
=> accounting: update accounting library for bugfix

core/oauth/domain/mapping.go
Cached claims from session override actual claims from token, even if subjectID in cached claims is different than in claims from token.
=> bugfix: cached claims overrides actual claims for wrong user in session

framework/web/context.go
span information got lost because the detached context was created by context.Background
=> framework/web: fix tracing in detached context

Readme.md, core/gotemplate/Readme.md
- Add "getting help" section
- Add answer to recent question to doc
=> Improve docs

framework/flamingo/sessions.go
=> session set correct options

docs/1. Flamingo Basics/8. Coding Conventions.md
=> document go:generate usage

core/healthcheck/module.go, core/oauth/infrastructure/healthcheck.go, core/oauth/module.go, framework/flamingo/healthcheck/fileSession.go, framework/flamingo/healthcheck/redisSession.go, framework/flamingo/sessions.go
=> move healthchecks to correct modules

core/oauth/application/authmanager.go
do not fail if no new idtoken was provided (i.e. only access token was
updated)
=> legacy patch oauth

framework/cmd/module.go
The signal was always leading to the "second interrupt signal received" case on the serve command
=> Remove SIGTERM from PersistantPostRun so that graceful shutdown can be used again for the serve command

framework/flamingo/sessions.go, framework/flamingo/sessions_test.go
Added possibility to pass redis database for storing session data
=> framework/flamingo: add possibility to specify redis store's database

core/auth/oauth/oidc.go
Co-authored-by: jeinfeldt <joerg.einfeldt@aoe.com>
=> delete session data if token retrieval fails

core/auth/oauth/module.go, core/auth/oauth/oauth.go, core/auth/oauth/oidc.go
Identifies incoming requests on the Authorization: Bearer header
=> feat(oauth): add oauth identifier

.github/workflows/semanticore.yml, CHANGELOG.md
This change adds Semanticore to automatically manage semantic releases
=> ci(semanticore): add semanticore

core/oauth/application/authmanager.go, core/oauth/module.go
see 860764857ae4611ea901c6d6fb0a7fcd0d9bd44a
=> feat(core/oauth): support issuer URL overriding

framework/flamingo/log.go
=> fix(framework/flamingo/log): added nil check for StdLogger and Logger Fix for #161

framework/opencensus/module.go
This fixes issue https://github.com/i-love-flamingo/flamingo/issues/304.
=> fix(framework/opencensus): x-correlation-id condition

Readme.md
=> fix: updating community join url to discord

core/silentzap/context.go, core/silentzap/logger.go
Writing with fields is not needed, since we all the time have fields, which are created using "WithField" and "WithFields"
=> fix(silentlogger): remove unnecessary fields

core/healthcheck/module.go, core/healthcheck/module_test.go, framework/flamingo/sessions.go
Start moving the configs to their respective module configs.
=> chore(session): health check config cleanup

core/gotemplate/Readme.md, docs/0. Introduction/1. Getting Started.md, docs/1. Flamingo Basics/2. Flamingo Project Structure.md
* update link to htmltemplate
* changed references from .html to .md to let mkdocs-material do its job (remove Warnings) - if there was a specific reason for referencing .html files, please let me know.
=> Small documentation updates for docs.flamingo.me

core/silentzap/levelencoder.go, core/silentzap/levels_standard.go, core/silentzap/levels_trace.go, core/silentzap/logger.go, core/silentzap/module.go, core/zap/levelencoder.go, core/zap/levels_standard.go, core/zap/levels_trace.go, core/zap/logger.go, core/zap/logger_test.go, core/zap/module.go, framework/flamingo/log.go, framework/flamingo/log_standard.go, framework/flamingo/log_test.go, framework/flamingo/log_trace.go
The logger implementation/interface within Flamingo does not support Trace level logging. This PR adds that functionality.
=> feat(log): Introduce Trace log level

framework/web/result.go
Fixes: https://github.com/i-love-flamingo/flamingo/issues/430
=> Fix attachment content disposition typo
